### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by lthibault** [roman-kachanovsky/go-binary-pack#1]
Performance is often a determining consideration when selecting an encoder.  Would you consider adding benchmarks to the tests and to the README?

**Comment by roman-kachanovsky** [comment]
Hi, Louis. Unfortunately, this is a small educational project to find out what Go is. Golang isn't my main language and I don't use the project at all. I'm even not sure that it works correctly in real cases. And I'm quite surprised that it's collected so many stars. So, I can add you as a collaborator or even try to transfer ownership, and you can do whatever you want if you really need this functionality and you know how to make it better.

**Comment by lthibault** [comment]
Hi Roman - thanks for the quick feedback, and congratulations for the accidentally-popular repo!

Thanks for the heads-up about the project state.  I'm afraid I don't have the time to take over maintenance on this project, but I appreciate the offer.

Happy coding!
